account/urls.py
from django.urls import path
from .views import user_login, register, logout_user

app_name = 'account'

urlpatterns = [
    path('login/', user_login, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register, name='register' )
   
]

blog/urls.py
from django.urls import path
from .views import index, PostDetailView, contact_us

app_name = 'blog'

urlpatterns = [
    path('', index, name='homepage'),
    path('<str:slug>/', PostDetailView.as_view(), name='detail-page'), 
    path('contact', contact_us, name='contact')
   
]

dashboard/urls.py
from django.urls import path
from .views import post_index, create_post, manage_user, create_user, manage_topic, create_topic, edit_post, delete_post, \
edit_user, delete_user, delete_topic, edit_topic

app_name = 'dashboard'

urlpatterns = [
    # for posts
  path('manage-post', post_index, name='post'),
  path('create-post', create_post, name='create-post'),
  path('edit/<str:slug>', edit_post, name='edit-post'),
  path('delete/<str:slug>', delete_post, name='post-delete'),

  # for users
  path('manage-user', manage_user, name='manage-user'), 
  path('create-user', create_user, name='create-user'), 
  path('ed/<int:pk>', edit_user, name='edit-user' ),
  path('del/<int:pk>', delete_user, name='user-delete' ),

  # for topic/categories
  path('manage-topic', manage_topic, name='manage-topic'), 
  path('create-topic', create_topic, name='create-topic'), 
  path('e/<slug:category_slug>', edit_topic, name='edit-topic'), 
  path('del/<slug:category_slug>', delete_topic, name='topic-delete'), 
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib.contenttypes.fields import GenericRelation
from hitcount.models import HitCountMixin, HitCount
from django.conf import settings
from ckeditor.fields import RichTextField

''''
This application have these models
1. Author/ user
2. Category
3. Post
4. Comment
---reply(ied) comments

'''


class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)
    total_posts = models.IntegerField(
        editable=False, verbose_name='num of posts in this category')
    category_slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)

    @property
    def total_posts(self):
        return self.posts.filter(status='published').count()

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['-created']


class Post(models.Model):

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250, unique=True)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='category')
    slug = models.SlugField(max_length=250)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    body = RichTextField()
    image = models.ImageField(upload_to='images/')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='draft')
    hit_count_generic = GenericRelation(
        HitCount, object_id_field='object_pk', related_query_name='hit_count_generic_relation')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog_app:post-detail', args=[str(self.slug)])


class BaseComment(models.Model):

    name = models.CharField(max_length=80)
    # parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)
    email = models.EmailField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
        abstract = True


class Comment(BaseComment):
    comment_body = models.TextField()
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    comment_slug = models.SlugField(max_length=100)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'


class RepliedComment(BaseComment):
    comment = models.ForeignKey(
        Comment, on_delete=models.CASCADE, related_name='reply_comments')
    reply_comment_body = models.TextField()

blog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Post, Category
from django.db.models import Q
from difflib import SequenceMatcher
from hitcount.views import HitCountDetailView
from django.urls import reverse
from django.conf import settings
from django.core.mail import send_mass_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.


def index(request):

    # Filtering by category
    all_categories = Category.objects.all()[:10]
    error = ''
    data = ''

    selected_category = request.GET.get("category")
    all_posts = Post.objects.filter(status='published')
    paginator = Paginator(all_posts, 20)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # if page is out of range, deliver the last page
        posts = paginator.page(paginator.num_pages)
    trending = Post.objects.filter(status='published').order_by(
        '-hit_count_generic__hits')[:10]

    if selected_category:
        all_posts = Post.objects.filter(
            category__name__icontains=selected_category)

    # Search
    if "search" in request.GET:

        data = request.GET.get("search")
        if data == '':
            error = "please enter a valid search"
        else:
            multiple_queries = Q(Q(title__icontains=data) | Q(
                category__name__icontains=data) | Q(body__icontains=data))
            all_posts = Post.objects.filter(multiple_queries)

    context = {
        "post": posts,
        'page':page,
        'all_categories': all_categories,
        'selected_category': selected_category,
        'trending': trending,
        'error': error,
        'data': data
    }
    return render(request, 'index.html', context)


class PostDetailView(HitCountDetailView):
    count_hit = True
    model = Post
    template_name = 'detail.html'
    context_object_name = 'trending_posts'

    def get(self, request, slug, *args, **kwargs):
        trending = Post.objects.order_by('-hit_count_generic__hits')[:10]

        all_categories = Category.objects.all()[:10]
        post = get_object_or_404(Post, slug=slug, status='published')

        # Get posts with the same category as the current post
        similar_posts = Post.objects.filter(category=post.category)

        # Filter out the current post from the similar posts
        similar_posts = similar_posts.exclude(slug=post.slug)

        # Compute similarity based on title
        similarity_threshold = 0.4

        similar_posts_filtered = []

        for x in similar_posts:
            similarity_ratio = SequenceMatcher(
                None, post.title, x.title).ratio()
            if similarity_ratio >= similarity_threshold:
                similar_posts_filtered.append(x)
        similar_posts_filtered = similar_posts_filtered[:7]

        context = {
            'item': post,
            'all_categories': all_categories,
            'similar_posts': similar_posts_filtered,
            'trending': trending

        }
        return render(request, 'detail.html', context)


def contact_us(request):
    sent = False
    success_message = ''
    if request.method == 'POST':
        message = request.POST.get('message')
        email = request.POST.get('email')
        subject = "Inquiry from Entire and Fit"

        # second part of the email
        second_subject = "Getting back to you"
        second_message = "Thank you for contacting us at Entire and Fit. We'll get back to you soon."
        sender_email = settings.EMAIL_HOST_USER
        recipient = [email]

        data_tuple = (
            (subject, message, email, [
             settings.EMAIL_HOST_USER, 'ejemstephen@gmail.com']),
            (second_subject, second_message, sender_email, recipient)
        )

        sent = send_mass_mail(data_tuple, fail_silently=False)
        if sent:
            success_message = "sent"

        return redirect('blog:homepage')
    context = {
        "success_message": success_message
    }

    return render(request, 'base.html', context)

blog/templates/base.html
{% load static %}



<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
    integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Candal|Lora" rel="stylesheet">

  <!-- Custom Styling -->
  <link rel="stylesheet" href="../static/css/style.css">

  <title>Entire and fit | {%block title%}{%endblock%}</title>
</head>

<body>
  <header>
    <div class="logo">
      <h1 class="logo-text">Entire<span>&</span>Fit</h1>
    </div>
    <i class="fa fa-bars menu-toggle"></i>
    <ul class="nav">
      <li><a href="{% url 'blog:homepage'%}">Home</a></li>
      <li><a href="#about">About</a></li>
      <li><a href="#">Services</a></li>

      {% if request.user.is_authenticated %}
      <li>
        <a href="#">
          <i class="fa fa-user"></i>
          {{request.user.username}}
          <i class="fa fa-chevron-down" style="font-size: .8em;"></i>
        </a>
        <ul>
          {% if request.user.role == "admin" or request.user.is_staff %}
          <li><a href="{% url 'dashboard:post' %}">Dashboard</a></li>
          {% endif %}
          <li><a href="{% url 'account:logout'%}" class="logout">Logout</a></li>
        </ul>
      </li>
      {%else%}

      <li><a style="color: rgb(248, 78, 78);" href="{% url 'account:register' %}">Sign Up</a></li> 
      <li><a style="color:rgb(5, 214, 5)" href="{% url 'account:login' %}">Login</a></li>
      {% endif %}
    </ul>
  </header>


{%block content%}{%endblock%}




  <!-- footer -->
  <div class="footer">
    <div class="footer-content">

      <div class="footer-section about" id="about">
        <h1 class="logo-text">Entire<span>&</span>Fit</h1>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.
            Minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat..
        </p>
        <div class="contact">
          <span><i class="fas fa-phone"></i> &nbsp; 081-2823-6032</span>
          <span><i class="fas fa-envelope"></i> &nbsp; info@entireandfit.com</span>
        </div>
        <div class="socials">
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <!-- <a href="#"><i class="fab fa-youtube"></i></a> -->
        </div>
      </div>

      <div class="footer-section links">
        <h2>Quick Links</h2>
        <br>
        <ul>
          <a href="#">
            <li>Team</li>
          </a>
          <a href="#">
            <li>Gallery</li>
          </a>
          <a href="#">
            <li>Terms and Conditions</li>
          </a>
        </ul>
      </div>

<!-- contact -->
      <div class="footer-section contact-form">
        <h2>Contact us</h2>
        <br>
        {% if success_message %}
    <div class="alert alert-success" role="alert">
        <p style="color:green">{{ success_message }}</p>
    </div>
    {% endif %}

        <form action="{% url 'blog:contact'%}" method="post">
          {%csrf_token%}
          <input type="email" name="email" class="text-input contact-input" placeholder="Your email address...">
          <textarea rows="4" name="message" class="text-input contact-input" placeholder="Your message..."></textarea>
          <button type="submit" class="btn btn-big contact-btn">
            <i class="fas fa-envelope"></i>
            Send
          </button>
        </form>
      </div>

    </div>

    <div class="footer-bottom">
      &copy; Entire&Fit | Designed by Ejembi Stephen
    </div>
  </div>
  <!-- // footer -->


  <!-- JQuery -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  <!-- Slick Carousel -->
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

  <!-- Custom Script -->
  <script src="{% static 'js/scripts.js' %}"></script>

</body>

</html>

blog/templates/detail.html
{% extends "base.html" %}

{%block title%}Read{%endblock%}
{% block content %}
  <!-- Page Wrapper -->
  <div class="page-wrapper">

    <!-- Content -->
    <div class="content clearfix">

      <!-- Main Content Wrapper -->
      <div class="main-content-wrapper">
        <div class="main-content single">
          <h1 class="post-title">{{item.title}}</h1>

          <div class="post-content">
            <p>{{item.body|safe}}
            </p>
          </div>

        </div>
      </div>
      <!-- // Main Content -->

      <!-- Sidebar -->
      <div class="sidebar single">

        <div class="fb-page" data-href="https://web.facebook.com/codingpoets/" data-small-header="false"
          data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
          <blockquote cite="https://web.facebook.com/codingpoets/" class="fb-xfbml-parse-ignore"><a
              href="https://web.facebook.com/codingpoets/">Coding Poets</a></blockquote>
        </div>


        <div class="section popular">
          <h2 class="section-title">Similar Posts</h2>
          {% for x in similar_posts %}
          <div class="post clearfix">
            <img src="{{x.image.url}}" alt="{{x.title}}">
            <a href="{% url 'blog:detail-page' slug=x.slug%}" class="title">
              <h4>{{x.title}}</h4>
            </a>
          </div>
          {% empty %}
          <p>No similar posts found.</p>
          {% endfor %}

     </div>

        <div class="section topics">
          <h2 class="section-title">Categories</h2>
          <ul>
            {%for item in all_categories %}
            <li><a href="{% url 'blog:homepage'%}?category={{item.name}}">{{item.name}}</a></li>
            {%endfor%}
          </ul>
        </div>
      </div>
      <!-- // Sidebar -->

    </div>
    <!-- // Content -->

  </div>
  <!-- // Page Wrapper -->

{%endblock%}

blog/templates/index.html
{% extends "base.html" %}
{% load hitcount_tags %}
{%block title%}Home{%endblock%}
{% block content %}
  <!-- Page Wrapper -->
  <div class="page-wrapper">

    <!-- Post Slider -->
    <div class="post-slider">
      <h1 class="slider-title">Trending Posts</h1>
      <i class="fas fa-chevron-left prev"></i>
      <i class="fas fa-chevron-right next"></i>

      <div class="post-wrapper">
{% for x in trending %}
        <div class="post">
          <img src="{{x.image.url}}" alt="{{x.title}}" class="slider-image">
          <div class="post-info">
            <h4><a href="{% url 'blog:detail-page' slug=x.slug %}">{{x.title|truncatewords:9}}</a></h4>
            <i class="far fa-user"> {{x.user.username}}</i>
            &nbsp;
            <i class="far fa-calendar"> {{x.created|date}}</i>  |
            &nbsp;
            <i class="far fa-eye"> {% get_hit_count for x%}</i>
          </div>
        </div>
{%endfor%}
      </div>

    </div>
    <!-- // Post Slider -->

    <!-- Content -->
    <div class="content clearfix">

      <!-- Main Content -->
      <div class="main-content">
        {% if selected_category %}
        <h1 class="recent-post-title">Posts for category: "{{ selected_category }}"</h1>
        {% elif data %}
        <h1 class="recent-post-title">Search Results for: "{{ data }}"</h1>

        {% else %}
        <h1 class="recent-post-title">All Posts</h1>
        {% endif %}

        {% if post %}
        <!-- Display posts for the selected category or search term -->
        <!-- Your code to display posts goes here -->
        {% else %}
        <div style="display: flex; justify-content: center; align-items: center;">
        <h4>{% if data %}No search results found{% else %}There are no posts in this category{% endif %}.</h4>
        </div>
    {% endif %}


{% for post in post %}

        <div class="post clearfix">
          <img src="{{post.image.url}}" alt="" class="post-image">
          <div class="post-preview">
            <h2><a href="{% url 'blog:detail-page' slug=post.slug%}">{{post.title}}</a></h2>

            <i class="far fa-list"> {{post.category}}</i> |
            &nbsp;
            <i class="far fa-user"> {{post.user.username}}</i>
            &nbsp;
            <i class="far fa-calendar"> {{post.created|date}}</i>
            |
            <i class="far fa-eye"> {%get_hit_count for post %}</i>
            &nbsp;
            <p class="preview-text">
             {{post.body|safe|truncatewords:30}}
            </p>
            <a href="{% url 'blog:detail-page' slug=post.slug%}" class="btn read-more">Read More</a>
          </div>
        </div>
{% endfor %}
      </div>
      <!-- // Main Content -->

      <div class="sidebar">

        <div class="section search">
          <h2 class="section-title">Search</h2>
          <p style="color: red;">{{error}}</p>
          <form action="{% url 'blog:homepage'%}" method="get">
            <input type="text" name="search" class="text-input" placeholder="Search...">
          </form>
        </div>


        <div class="section topics">
          <h2 class="section-title">Categories</h2>
          <ul>
            {%for item in all_categories %}
            <li><a href="{% url 'blog:homepage'%}?category={{item.name}}">{{item.name}}</a></li>
            {%endfor%}
          </ul>
        </div>

      </div>

    </div>
    <!-- // Content -->
    {% include "pagination.html" with page=post %}
  </div>
  <!-- // Page Wrapper -->

  {% endblock %}

blog/templates/pagination.html
<div class="pagination" style="margin-top: 60px; margin-bottom: 60px; text-align: center;">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}" style="padding: 5px 10px; margin: 0 5px; color: #333; text-decoration: none; border: 1px solid #ccc; border-radius: 5px;">Previous</a>
        {% endif %}
        <span class="current" style="padding: 5px 10px; margin: 0 5px; color: #fff; background-color: #006669; border: 1px solid #006669; border-radius: 5px;">Page {{ page.number }} of {{ page.paginator.num_pages }}.</span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}" style="padding: 5px 10px; margin: 0 5px; color: #333; text-decoration: none; border: 1px solid #ccc; border-radius: 5px;">Next</a>
        {% endif %}
    </span>
</div>