blog/urls.py
from django.urls import path
from .views import index, PostDetailView, contact_us

app_name = 'blog'

urlpatterns = [
    path('', index, name='homepage'),
    path('<str:slug>/', PostDetailView.as_view(), name='detail-page'), 
    path('contact', contact_us, name='contact')
   
]

dashboard/urls.py
from django.urls import path
from .views import post_index, create_post, manage_user, create_user, manage_topic, create_topic, edit_post, delete_post, \
edit_user, delete_user, delete_topic, edit_topic

app_name = 'dashboard'

urlpatterns = [
    # for posts
  path('manage-post', post_index, name='post'),
  path('create-post', create_post, name='create-post'),
  path('edit/<str:slug>', edit_post, name='edit-post'),
  path('delete/<str:slug>', delete_post, name='post-delete'),

  # for users
  path('manage-user', manage_user, name='manage-user'), 
  path('create-user', create_user, name='create-user'), 
  path('ed/<int:pk>', edit_user, name='edit-user' ),
  path('del/<int:pk>', delete_user, name='user-delete' ),

  # for topic/categories
  path('manage-topic', manage_topic, name='manage-topic'), 
  path('create-topic', create_topic, name='create-topic'), 
  path('e/<slug:category_slug>', edit_topic, name='edit-topic'), 
  path('del/<slug:category_slug>', delete_topic, name='topic-delete'), 
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from blog.models import Post, Category
from account.models import User
from django.urls import reverse
from account.utils import check_category_exists, check_username_exists
from django.db import IntegrityError
from django.utils.text import slugify
from django.contrib.auth.hashers import make_password
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.


def post_index(request):
    all_posts = Post.objects.all().order_by('id')
    paginator = Paginator(all_posts, 20 )
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # if page is out of range, deliver the last page
        posts = paginator.page(paginator.num_pages)

    context = {
        'all_posts': posts
    }

    return render(request, 'dashboard/post_index.html', context=context)

def edit_post(request, slug):
    all_categories = Category.objects.all()
    author_list = ['author', 'admin']
    all_authors = User.objects.filter(role__in=author_list)

    post = get_object_or_404(Post, slug=slug)
    if request.method == "POST":

        # Check if the image fields is empty in the form data
        if not request.FILES.get('image'):
            # if no new image is uploaded, retain the original image
            image = post.image
        else:
            # If no new image is uploaded, retain the orginal image
            image = request.FILES.get("image")

        # Extract form data from request.POST
        title = request.POST.get('title')
        body = request.POST.get('body')
        # image = request.FILES.get('image')
        category_slug = request.POST.get('category')
        user_id = request.POST.get('author')
        status = request.POST.get('status')

        # update post fields with new data
        post.title = title
        post.body = body
        post.image = image  # Assign the new or existing image
        # update category and author using related objects or IDs
        post.category.category_slug = category_slug
        post.user_id = user_id
        post.status = status
        # Save the updated post
        post.save()

        return redirect(reverse('dashboard:post'))
    edit = True
    context = {
        "post": post,
        "edit": edit,
        "all_categories": all_categories,
        "all_authors": all_authors,
    }
    return render(request, 'dashboard/post_create.html', context)

def delete_post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == 'POST':
        # Delete the post
        post.delete()
        return redirect(reverse('dashboard:post'))
    return render(request, 'dashboard/post_index.html')

def create_post(request):
    all_categories = Category.objects.all()
    author_list = ['author', 'admin']
    all_authors = User.objects.filter(role__in=author_list)

    error = ''
    if request.method == "POST":
        data = request.POST
        file = request.FILES
        title = data.get('title')
        slug = slugify(title)
        body = data.get('body')
        image = file.get('image')
        category_slug = data.get('category')
        category_slug = slugify(category_slug)
        user_id = data.get('author')
        status = data.get('status')

        if title == '':
            error = "Please enter title"
        elif image == None:
            error = "Image field is required"
        elif body == '':
            error = "Body field is required"
        else:
            try:
                category = Category.objects.get(category_slug=category_slug)
                author = User.objects.get(id=user_id)

                Post.objects.create(title=title, slug=slug,
                                    body=body, image=image, category=category, user=author, status=status)
                return redirect(reverse('dashboard:post'))

            except IntegrityError:
                error = "There is an issue with the title"
    context = {
        "error": error,
        "all_categories": all_categories,
        "all_authors": all_authors,
    }
    return render(request, 'dashboard/post_create.html', context=context)


def manage_user(request):
    all_users = User.objects.all().order_by('id')
    paginator = Paginator(all_users, 20 )
    page = request.GET.get('page')
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer deliver the first page
        users = paginator.page(1)
    except EmptyPage:
        # if page is out of range, deliver the last page
        users = paginator.page(paginator.num_pages)

    context = {
        "users": users
    }
    return render(request, 'dashboard/user_index.html', context=context)

def edit_user(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == "POST":
        data = request.POST
        username = data.get('username')
        email = data.get('email')
        password = data.get('password')
        role = data.get('role')

        # Check for password matching
        if password != data.get('passwordConf'):
            error = "Passwords didn't match"
        else:
            # Update user details
            user.username = username
            user.email = email
            if password:
                user.set_password(password)  # Hash the password
            user.role = role
            user.save()
            return redirect(reverse('dashboard:manage-user'))
    else:
        error = ''

    edit = True
    context = {
        "edit": edit,
        "user": user,
        "error": error
    }
    return render(request, 'dashboard/user_create.html', context)

def delete_user(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        # Delete the post
        user.delete()
        return redirect(reverse('dashboard:manage-user'))
    return render(request, 'dashboard/user_index.html')

def create_user(request):
    error = ''
    if request.method == "POST":
        data = request.POST
        username = data.get('username')
        email = data.get('email')
        password = data.get('password')
        hashed_password = make_password(password)
        password_conf = data.get('passwordConf')
        role = data.get('role')

        if password != password_conf:
            error = "passwords didn't match"
        elif check_username_exists(username):
            error = "this username already exists"
        else:
            try:
                User.objects.create(
                    username=username, email=email, password=hashed_password, role=role)
                return redirect(reverse('dashboard:manage-user'))
            except Exception as e:
                error = f"{e}"
    context = {
        "error": error
    }
    return render(request, 'dashboard/user_create.html', context=context)


def manage_topic(request, edit_category_slug=None, delete_category_slug=None):
    all_topics = Category.objects.all().order_by('id')
    paginator = Paginator(all_topics, 20 )
    page = request.GET.get('page')
    try:
        topics = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer deliver the first page
        topics = paginator.page(1)
    except EmptyPage:
        # if page is out of range, deliver the last page
        topics = paginator.page(paginator.num_pages)
    context = {
        "all_topics": topics
    }
    return render(request, 'dashboard/topic_index.html', context=context)

def create_topic(request):
    error = ''
    if request.method == "POST":
        data = request.POST
        name = data.get('name', '')
        slug = slugify(name)
        if name.isalpha():
            name = name.title()
            try:
                Category.objects.create(name=name, category_slug=slug)
                return redirect(reverse('dashboard:manage-topic'))
            except IntegrityError:
                error = "This category/topic name already exists"
        else:
            error = "Invalid category/topic name"

    context = {
        "error": error
    }
    return render(request, 'dashboard/topic_create.html', context=context)

def edit_topic(request, category_slug):
    category = get_object_or_404(Category, category_slug=category_slug)
    if request.method == 'POST':
        data = request.POST

        # extract category from the data
        name = data.get('name')
        slug = slugify(name)

        # update the category field with the new data
        category.name = name
        category.category_slug = slug

        # save the updated category
        category.save()
        return redirect(reverse('dashboard:manage-topic'))
    edit = True
    context = {
        "edit": edit,
        "category": category
    }
    return render(request, 'dashboard/topic_create.html', context)

def delete_topic(request, category_slug):
    category = get_object_or_404(Category, category_slug=category_slug)
    if request.method == "POST":
        category.delete()
        return redirect(reverse('dashboard:manage-topic'))
    return render(request, 'dashboard/topic_index.html')

dashboard/templates/dashboard/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- Font Awesome -->
        <link rel="stylesheet"
            href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
            integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
            crossorigin="anonymous">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Candal|Lora"
            rel="stylesheet">

        <!-- Custom Styling -->
        <link rel="stylesheet" href="../../static/css/style.css">

        <!-- Admin Styling -->
        <link rel="stylesheet" href="../../static/css/admin.css">

        <title>Dashboard | {%block title%}{%endblock%}</title>
    </head>

    <body>
        <header>
            <div class="logo">
                <h1 class="logo-text">Entire<span>&</span>Fit</h1>
            </div>
            <i class="fa fa-bars menu-toggle"></i>
            <ul class="nav">
                {% if request.user.is_authenticated %}
                <li>
                    <a href="#">
                        <i class="fa fa-user"></i>
                        {{request.user.username}}
                        <i class="fa fa-chevron-down" style="font-size: .8em;"></i>
                    </a>
                    <ul>
                        <li><a href="{% url 'blog:homepage'%}" class="logout">Logout</a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </header>


        <!-- Admin Page Wrapper -->
        <div class="admin-wrapper">

            <!-- Left Sidebar -->
            <div class="left-sidebar">
                <ul>
                    <li><a href="{% url 'dashboard:post' %}">Manage Posts</a></li>
                    <li><a href="{% url 'dashboard:manage-user' %}">Manage Users</a></li>
                    <li><a href="{% url 'dashboard:manage-topic' %}">Manage Topics</a></li>
                </ul>
            </div>
            <!-- // Left Sidebar -->

            
        {%block content%} {%endblock%}


            

        <!-- JQuery -->
        <script
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Ckeditor -->
    <script
        src="https://cdn.ckeditor.com/ckeditor5/12.2.0/classic/ckeditor.js"></script>
    <!-- Custom Script -->
    <script src="{% static 'js/scripts1.js' %}"></script>

</body>

</html>

dashboard/templates/dashboard/pagination.html
<div class="pagination" style="margin-top: 60px; margin-bottom: 60px; text-align: center;">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}" style="padding: 5px 10px; margin: 0 5px; color: #333; text-decoration: none; border: 1px solid #ccc; border-radius: 5px;">Previous</a>
        {% endif %}
        <span class="current" style="padding: 5px 10px; margin: 0 5px; color: #fff; background-color: #006669; border: 1px solid #006669; border-radius: 5px;">Page {{ page.number }} of {{ page.paginator.num_pages }}.</span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}" style="padding: 5px 10px; margin: 0 5px; color: #333; text-decoration: none; border: 1px solid #ccc; border-radius: 5px;">Next</a>
        {% endif %}
    </span>
</div>

dashboard/templates/dashboard/post_create.html
{% extends "dashboard/base.html" %}
{% load method_override %}

{%block title%}Create post{%endblock%}
{% block content %}

            <!-- Admin Content -->
            <div class="admin-content">
                <div class="button-group">
                    <a href="{% url 'dashboard:create-post' %}" class="btn btn-big">Add Post</a>
                    <a href="{% url 'dashboard:post' %}" class="btn btn-big">Manage Posts</a>
                </div>


                <div class="content">

                    {% if edit %}
                    <h2 class="page-title">Edit Post</h2>
                    {% else %}
                    <h2 class="page-title">Create Post</h2>
                    {% endif %}

                <p style="color: red;">{{error}}</p>
                
                <form action="{% if edit %}{% url 'dashboard:edit-post' post.slug %}{% else %}{% url 'dashboard:create-post' %}{% endif %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% if edit %}
                    <input type="hidden" name="_method" value="PUT">
                    {% endif %}
                    <div>
                        <label>Title</label>
                        {% if edit %}
                            <input type="text" name="title" class="text-input" value="{{ post.title }}">
                        {% else %}
                            <input type="text" name="title" class="text-input" value="">
                        {% endif %}
                    </div>
                    <div>
                        <label>Body</label>
                        {% if edit %}
                            <textarea name="body" id="body" class="text-input">{{ post.body }}</textarea>
                        {% else %}
                            <textarea name="body" id="body" class="text-input"></textarea>
                        {% endif %}
                    </div>
                    <div>
                        <label>Image</label>
                        <input type="file" name="image" class="text-input">
                    </div>
                    <div>
                        <label>Category</label>
                        <select name="category" class="text-input">
                            {% for x in all_categories %}
                                {% if edit %}
                                    {% if x.category_slug == post.category.category_slug %}
                                    
                                        <option value="{{ x.category_slug }}" selected>{{ x.name }}</option>
                                    {% else %}
                                        <option value="{{ x.category_slug }}">{{ x.name }}</option>
                                    {% endif %}
                                {% else %}
                                    <option value="{{ x.category_slug }}">{{ x.name }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                        
                    </div>
                    <div>
                        <label>Author</label>
                        <select name="author" class="text-input">
                            {% for a in all_authors %}
                                {% if edit and a.id == post.author.id %}
                                    <option value="{{ a.id }}" selected>{{ a.username }}</option>
                                {% else %}
                                    <option value="{{ a.id }}">{{ a.username }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                        
                    </div>
                    <div>
                        <label>Status</label>
                        <select name="status" class="text-input">
                            <option value="draft" {% if edit and post.status == 'draft' %}selected{% endif %}>Draft</option>
                            <option value="published" {% if edit and post.status == 'published' %}selected{% endif %}>Published</option>
                        </select>
                    </div>
                    <div>
                        <button type="submit" class="btn btn-big">{% if edit %}Update Post{% else %}Add Post{% endif %}</button>
                    </div>
                </form>

                </div>

            </div>
            <!-- // Admin Content -->

        </div>
        <!-- // Page Wrapper -->
{%endblock%}

dashboard/templates/dashboard/post_index.html
{% extends "dashboard/base.html" %}
{% load method_override %}
{%block title%}manage post{%endblock%}

{% block content %}

            <!-- Admin Content -->
            <div class="admin-content">
                <div class="button-group">
                    <a href="{% url 'dashboard:create-post' %}" class="btn btn-big">Add Post</a>
                    <a href="{% url 'dashboard:post' %}" class="btn btn-big">Manage Posts</a>
                </div>


                <div class="content">

                    <h2 class="page-title">Manage Posts</h2>

                    <table>
                        <thead>
                            <th>SN</th>
                            <th>Title</th>
                            <th>Author</th>
                            <th>Status</th>
                            <th colspan="3">Action</th>
                        </thead>
                        <tbody>
                            {% for post in all_posts %}
                            <tr>
                                <td>{{post.id}}</td>
                                <td>{{post.title}}</td>
                                <td>{{post.user.username}}</td>
                                <td class="publish">{{post.status}}</td>
                                <td><a href="{% url 'dashboard:edit-post' post.slug %}" class="edit">Edit</a></td>
                                <td><form action="{% url 'dashboard:post-delete' post.slug %}" method="post" id="delete-form">
                                    {% csrf_token %}
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="submit" value="Delete" class="delete">
                                </form></td>
                            </tr>
                            {% endfor %}

                        </tbody>
                    </table>

                </div>
                {% include "pagination.html" with page=all_posts %}
            </div>
            <!-- // Admin Content -->
            
        </div>
        <!-- // Page Wrapper -->
{%endblock%}

dashboard/templates/dashboard/topic_create.html
{% extends "dashboard/base.html" %}

{%block title%}create topic{%endblock%}
{% block content %}

            <!-- Admin Content -->
            <div class="admin-content">
                <div class="button-group">
                    <a href="{% url 'dashboard:create-topic' %}" class="btn btn-big">Add Topic</a>
                    <a href="{% url 'dashboard:manage-topic' %}" class="btn btn-big">Manage Topics</a>
                </div>


                <div class="content">

                    <h2 class="page-title">{% if edit %}Edit Topic{% else %}Add Topic{% endif %}</h2>

                    <form action="{% if edit %}{% url 'dashboard:edit-topic' category.category_slug %}{% else %}{% url 'dashboard:create-topic' %}{% endif %}" method="post">
                        {% csrf_token %}
                        <p style="color: red;">{{ error }}</p>
                        <div>
                            <label>Name</label>
                            <input type="text" required name="name" class="text-input" value="{% if edit %}{{ category.name }}{% endif %}">
                        </div>
                    
                        <div>
                            <button type="submit" class="btn btn-big">{% if edit %}Update Topic{% else %}Add Topic{% endif %}</button>
                        </div>
                    </form>
                    

                </div>

            </div>
            <!-- // Admin Content -->

        </div>
{%endblock%}

dashboard/templates/dashboard/topic_index.html
{% extends "dashboard/base.html" %}

{%block title%}manage topics{%endblock%}
{% block content %}

            <!-- Admin Content -->
            <div class="admin-content">
                <div class="button-group">
                    <a href="{% url 'dashboard:create-topic' %}" class="btn btn-big">Add Topic</a>
                    <a href="{% url 'dashboard:manage-topic' %}" class="btn btn-big">Manage Topics</a>
                </div>


                <div class="content">

                    <h2 class="page-title">Manage Topics</h2>

                    <table>
                        <thead>
                            <th>SN</th>
                            <th>Name</th>
                            <th colspan="2">Action</th>
                        </thead>
                        <tbody>
                            {% for topic in all_topics %}
                            <tr>
                                <td>{{topic.id}}</td>
                                <td>{{topic.name}}</td>
                                <td><a href="{% url 'dashboard:edit-topic' topic.category_slug  %}" class="edit">edit</a></td>
                                
                                <td><form action="{% url 'dashboard:topic-delete' topic.category_slug %}" method="post" id="delete-form">
                                    {% csrf_token %}
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="submit" value="Delete" class="delete">
                                </form></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
                {% include "pagination.html" with page=all_topics %}
            </div>
            <!-- // Admin Content -->

        </div>
        <!-- // Page Wrapper -->
{%endblock%}

dashboard/templates/dashboard/user_create.html
{% extends "dashboard/base.html" %}

{%block title%}create users{%endblock%}
{% block content %}
            <!-- Admin Content -->
            <div class="admin-content">
                <div class="button-group">
                    <a href="{% url 'dashboard:create-user' %}" class="btn btn-big">Add User</a>
                    <a href="{% url 'dashboard:manage-user' %}" class="btn btn-big">Manage Users</a>
                </div>


                <div class="content">

                    <h2 class="page-title">{% if edit %}Edit User{% else %}Add User{% endif %}</h2>

                    <p style="color: red;">{{ error }}</p>
                    
                    <form action="{% if edit %}{% url 'dashboard:edit-user' user.id %}{% else %}{% url 'dashboard:create-user' %}{% endif %}" method="post">
                        {% csrf_token %}
                        <div>
                            <label>Username</label>
                            <input type="text" name="username" class="text-input" value="{{ user.username }}">
                        </div>
                        <div>
                            <label>Email</label>
                            <input type="email" name="email" class="text-input" value="{{ user.email }}">
                        </div>
                        <div>
                            <label>Password</label>
                            <input type="password" name="password" class="text-input">
                        </div>
                        <div>
                            <label>Password Confirmation</label>
                            <input type="password" name="passwordConf" class="text-input">
                        </div>
                        <div>
                            <label>Role</label>
                            <select name="role" class="text-input">
                                <option value="reader" {% if user.role == 'reader' %}selected{% endif %}>Reader</option>
                                <option value="author" {% if user.role == 'author' %}selected{% endif %}>Author</option>
                                <option value="admin" {% if user.role == 'admin' %}selected{% endif %}>Admin</option>
                            </select>
                        </div>
                        <div>
                            <button type="submit" class="btn btn-big">{% if edit %}Update User{% else %}Add User{% endif %}</button>
                        </div>
                    </form>
                    

                </div>

            </div>
            <!-- // Admin Content -->

        </div>
        <!-- // Page Wrapper -->
{%endblock%}

dashboard/templates/dashboard/user_index.html
{% extends "dashboard/base.html" %}

{%block title%}manage users{%endblock%}
{% block content %}


            <!-- Admin Content -->
            <div class="admin-content">
                <div class="button-group">
                    <a href="{% url 'dashboard:create-user' %}" class="btn btn-big">Add User</a>
                    <a href="{% url 'dashboard:manage-user' %}" class="btn btn-big">Manage Users</a>
                </div>


                <div class="content">

                    <h2 class="page-title">Manage Users</h2>

                    <table>
                        <thead>
                            <th>SN</th>
                            <th>Username</th>
                            <th>Role</th>
                            <th colspan="2">Action</th>
                        </thead>
                        <tbody>
                            {% for user in users %}
                            <tr>
                                <td>{{user.id}}</td>
                                <td>{{user.username}}</td>
                                <td>{{user.role}}</td>
                                <td><a href="{% url 'dashboard:edit-user' user.id%}" class="edit">edit</a></td>
                                <td><form action="{% url 'dashboard:user-delete' user.id %}" method="post" id="delete-form">
                                    {% csrf_token %}
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="submit" value="Delete" class="delete">
                                </form></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
                {% include "pagination.html" with page=users %}
            </div>
            <!-- // Admin Content -->
        </div>
        <!-- // Page Wrapper -->

{%endblock%}